<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Product_model extends CI_Model
{

    public $table = 'product';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('kategori', $q);
	$this->db->or_like('ukuran', $q);
	$this->db->or_like('tebal_daun_pintu', $q);
	$this->db->or_like('tebal_plat_daun_pintu', $q);
	$this->db->or_like('tebal_plat_kusen_pintu', $q);
	$this->db->or_like('insulation', $q);
	$this->db->or_like('engsel', $q);
	$this->db->or_like('fire_rated', $q);
	$this->db->or_like('overlap_bibir_pintu', $q);
	$this->db->or_like('aksesoris', $q);
	$this->db->or_like('tebal_frame_kisi', $q);
	$this->db->or_like('tebal_rangka_pintu', $q);
	$this->db->or_like('sliding_gear', $q);
	$this->db->or_like('foto', $q);
	$this->db->or_like('galery', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('kategori', $q);
	$this->db->or_like('ukuran', $q);
	$this->db->or_like('tebal_daun_pintu', $q);
	$this->db->or_like('tebal_plat_daun_pintu', $q);
	$this->db->or_like('tebal_plat_kusen_pintu', $q);
	$this->db->or_like('insulation', $q);
	$this->db->or_like('engsel', $q);
	$this->db->or_like('fire_rated', $q);
	$this->db->or_like('overlap_bibir_pintu', $q);
	$this->db->or_like('aksesoris', $q);
	$this->db->or_like('tebal_frame_kisi', $q);
	$this->db->or_like('tebal_rangka_pintu', $q);
	$this->db->or_like('sliding_gear', $q);
	$this->db->or_like('foto', $q);
	$this->db->or_like('galery', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Product_model.php */
/* Location: ./application/models/Product_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-11-11 16:00:48 */
/* http://harviacode.com */